config/routes.rb
Rails.application.routes.draw do
  # get 'users/index'
  # get 'users/show'
  # get 'users/edit'
  devise_for :users
  root to: "homes#top"
  get "/home/about" => "homes#about", as: "about"
  
  resources :books do
    resources :book_comments, only: [:create, :destroy]
    resource :favorites, only: [:create, :destroy]
    
  end
  resources :users
  # get 'books/new'
  # get 'books/index'
  # get 'books/show'
  # resources :books, only: [:index, :show]
  # get "home/about"=>"homes#about"
  # root to: "homes#top"
  # devise_for :users
  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  # has_one_attached :profile_image
  has_many :book_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  belongs_to :user
  
  validates :title,presence:true
  # 最大２百字まで（length:(maximum:200)）
  	validates :body,presence:true,length:{maximum:200}
  	
  	
  	
  def favorited_by?(user)
    favorites.exists?(user_id: user.id)
  end
   
end

app/models/book_comment.rb
class BookComment < ApplicationRecord
  belongs_to :user
  belongs_to :book
  validates :comment, presence: true

end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :book
  
  validates_uniqueness_of :book_id, scope: :user_id
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_one_attached :profile_image
  has_many :book_comments, dependent: :destroy
  has_many :books, dependent: :destroy
  has_many :favorites, dependent: :destroy
  validates :name, length: { minimum: 2, maximum: 20 }, uniqueness: true
  validates :introduction, length: { maximum: 50 }



  # def get_image
  #   if image.attached?
  #     image
  #   else
  #     'no_image.jpg'
  #   end
  # end

  def get_profile_image(size)
    unless profile_image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      profile_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    profile_image.variant(resize: size).processed
  end
#   # mmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmm
  # def get_profile_image(size)
  #   unless profile.image.attached?
  #     file_path = Rails.root.join('app/assets/images/no_image.jpg')
  #     image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
  #   end
  #   image
  # end
#   profile_image.variant(resize: size).processed
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(resource)
    user_path(resource)
  end

  def after_sign_out_path_for(resource)
    root_path
  end
  
  
  # private

  #   def configure_permitted_parameters
  #   # devise_parameter_sanitizer.permit(:sign_up, keys: [:name)
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:name])
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:name])
  #   end
private

    def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up,keys:[:name, :email]) # 注目
    end
  # def configure_permitted_parameters
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  # end
end

app/controllers/book_comments_controller.rb
class BookCommentsController < ApplicationController
  def create
    book = Book.find(params[:book_id])
    comment = current_user.book_comments.new(book_comment_params)
    comment.book_id = book.id
    comment.save!
    redirect_to request.referer
  end

  def destroy
    BookComment.find_by(id: params[:id], book_id: params[:book_id]).destroy
    redirect_to request.referer
  end

  private
  def book_comment_params
    params.require(:book_comment).permit(:comment)
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :authenticate_user!
  before_action :is_matching_login_user, only: [:edit, :update, :destroy]

  def show
    @book = Book.find(params[:id])
    # @book_comment = BookComment.new
    @book_comment = BookComment.new

  end

  def index
    @books = Book.all
    @book = Book.new

  end

  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    if @book.save
      flash[:notice] ="You have created book successfully."
      redirect_to book_path(@book)
    else
      @books = Book.all
      render 'index'
    end
  end

  def edit
    @book = Book.find(params[:id])
  end

  def update
    if @book.update(book_params)
       flash[:notice] ="You have updated book successfully."
      redirect_to book_path(@book)
    else
      render "edit"
    end
  end

  def destroy
    @book.destroy
    redirect_to books_path
  end

  private

  def book_params
    params.require(:book).permit(:title, :body)
  end

  def is_matching_login_user
    @book = Book.find(params[:id])
    unless @book.user == current_user
      redirect_to books_path
    end
    
  end
  
  
  
  #


  # def index
  #   @book = Book.new
  # end

  # def show
  # end
  
  # # 投稿データの保存
  # def create
  #   @book = book.new(post_image_params)
  #   @book.user_id = current_user.id
  #   @book.save
  #   redirect_to book_path
  # end
  
  # # 投稿データのストロングパラメータ
  # private

  # def book_params
  #   params.require(:book).permit(:title, :body)
  # end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  def create
    book = Book.find(params[:book_id])
    favorite = current_user.favorites.new(book_id: book.id)
    favorite.save
    redirect_to request.referer
  end

  def destroy
    book = Book.find(params[:book_id])
    favorite = current_user.favorites.find_by(book_id: book.id)
    favorite.destroy
    redirect_to request.referer
  end

end



# class FavoritesController < ApplicationController
#   def create
#     book = Book.find(params[:book_id])
#     favorite = current_user.favorites.new(book_id: book.id)
#     favorite.save
#     redirect_to request.referer
#   end

#   def destroy
#     book = Book.find(params[:book_id])
#     favorite = current_user.favorites.find_by(book_id: book.id)
#     favorite.destroy
#     redirect_to request.referer
#   end
# end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  before_action :is_matching_login_user, only: [:edit, :update]

  def show
    @user = User.find(params[:id])
    @books = @user.books
    @book = Book.new
  end

  def index
    @users = User.all
    @book = Book.new
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    if @user.update(user_params)
       flash[:notice] ="You have updated user successfully."
      redirect_to user_path(@user)
    else
      render "edit"
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :introduction, :profile_image)
  end

  def is_matching_login_user
    @user = User.find(params[:id])
    unless @user == current_user
      redirect_to user_path(current_user)
    end
  end
  
  
  
  
  
  
  
  
  
  
  
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/book_comments_helper.rb
module BookCommentsHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/book_comments/_form.html.erb
<%= form_with(model:[book, book_comment], local: true) do |f| %>
    <%= f.text_area :comment,placeholder: "コメント", class: "w-100" %>
    <%= f.submit "送信", class: "btn btn-lg btn-base-1 mt-20 pull-right" %>
<% end %>

app/views/book_comments/_index.html.erb
<table>
  <tbody>
    

    <% book.book_comments.each do |book_comment| %>
      <tr>
        <td>
          <%= link_to user_path(book_comment.user) do %>
            <%= image_tag book_comment.user.get_profile_image( "50x50" ) %><br>
            <%= book_comment.user.name %>
          <% end %>
          
       
        </td>
        <td><%= book_comment.comment %></td>
        <td>
          <% if book_comment.user == current_user %>
            <%= link_to "Destroy", book_book_comment_path(book, book_comment), method: :delete, class: "btn btn-danger pull-right" %>
          <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/books/_form.html.erb
<%= form_with model:book,local:true do |f| %>
  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title, class: 'form-control book_title' %>
  
    <%= f.label :opinion %>
    <%= f.text_area :body, class: 'form-control book_body' %>
    </br>
 
    <%= f.submit class: 'btn btn-success' %>
  </div>
<% end %>

app/views/books/_index.html.erb
<table class='table table-hover table-inverse'>
  <thead>
    <tr>
      <th></th>
      <th>Title</th>
      <th>Opinion</th>
      <th ></th>
    </tr>
  </thead>
  <tbody>
    <% books.each do |book| %>
      <tr>
        <td>
          <%= link_to user_path(book.user) do %>
            <%= image_tag book.user.get_profile_image('100x100') %>
          <% end %>
        </td>
        <td><%= link_to book.title,book, class: "book_#{book.id}" %></td>
        <td><%= book.body %></td>
        <td><%= render "favorites/good", book: book %></td>
        <td>コメント数: <%= book.book_comments.count %></td>

      </tr>
    <% end %>
  </tbody>
</table>

app/views/books/edit.html.erb
<div class='container'>
  <div class='row'>
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
  		<h1>Editing Book</h1>
    	<%= render 'layouts/errors', user: @book %>
  		<%= render 'form', book: @book %>
  		<%= link_to 'Show', @book, class: "book_#{@book.id}" %> |
  		<%= link_to 'Back', books_path, class: "back" %>
  </div>
</div>

app/views/books/index.html.erb
<div class='container'>

  <%= render 'layouts/errors', user: @book %>
  <div class='row'>
    <div class='col-md-3'>
      <h2>User info</h2>
      <%= render 'users/info', user: current_user %>
      <h2 class="col">New book</h2>
      <%= render 'form', book: @book %>
    </div>
    <div class='col-md-8 offset-md-1'>
      <h2>Books</h2>
      <%= render 'index', books: @books%>
    </div>
  </div>
</div>

app/views/books/show.html.erb
<div class='container'>
   <%= render 'layouts/success' %>
  <div class='row'>
    <div class='col-md-3'>
      <h2>User info</h2>
      <%= render 'users/info', user: @book.user %>
      <h2 class="mt-3">New book</h2>
      <%= render 'form', book: Book.new %>
    </div>
    <div class='col-md-8 offset-md-1'>
  		<h2>Book detail</h2>
  		<table class='table'>
  		  <tr>
  		    

          
            <td>
              <%= link_to user_path(@book.user) do %>
                <%= image_tag @book.user.get_profile_image("100x100") %><br><br>
                <%= @book.user.name %>
              <% end %>
            </td>
            <td><%= link_to @book.title, @book %></td>
            <td><%= @book.body %></td>
            <td><%= render "favorites/good", book: @book %></td>
            <td>コメント数: <%= @book.book_comments.count %></td>
          <% if @book.user == current_user %>
            <td><%= link_to 'Edit', edit_book_path(@book), class: "btn btn-sm btn-success " %></td>
            <td><%= link_to 'Destroy', @book, method: :delete, data: { confirm: '本当に消しますか？' }, class: "btn btn-sm btn-danger" %></td>
          <% end %>
          
        </tr>
      </table>
      <%= render "book_comments/index", book: @book %>
      <%= render "book_comments/form", book: @book, book_comment: @book_comment %>
    </div>
  </div>
</div>

app/views/favorites/_good.html.erb
<% if book.favorited_by?(current_user) %>
  <%= link_to book_favorites_path(book), method: :delete do %>
    <i class="fas fa-heart" aria-hidden="true" style="color: red;"></i>
    <%= book.favorites.count %> 
  <% end %>
<% else %>
  <%= link_to book_favorites_path(book), method: :post do %>
    <i class="fas fa-heart" aria-hidden="true"></i>
    <%= book.favorites.count %> 
  <% end %>
<% end %>

app/views/homes/about.html.erb
<html>
  <!--<main>-->
    <p id="notice"></p>
    <div class="container">
      <div class="row">
        <h1 class="px-3 mx-auto">
          Welcome to
          <i class="fas fa-book" arire-hidden="true">
          </i>
          <strong>
            Bookers
          </strong>
          !
        </h1>
      </div>
    </div>
  <!--</main>-->
</html>
  

app/views/homes/top.html.erb
<html
     <%= render 'layouts/success' %>

    <p id="notice"></p>
    <div class="container">
  <div class="row">
    <div class="mx-auto col-11 col-sm-10 col-lg-8 col-xl-6">
      <h1>welcome to <i class="fas fa-book" aria-hidden="true"></i><strong>Bookers</strong>  !!</h1>
      <p>In  <i class="fas fa-book" aria-hidden="true"></i><strong>Bookers</strong>, </p>
      <p>you can share and exchange  your opinions , inpressions , and emotions</p>
      <p> about various books!</p>
      <div class="btn-wrapper col-10 mx-auto">
        <div class="row">
          <!--<a class="btn btn-info btn-sm btn-block mb-3 sign_in" , new_user_session_path>Log in</a>-->
          <%= link_to "Log in", new_user_session_path, class: 'nav-link text-white btn btn-info btn-sm btn-block mb-3 sign_in' %>
        </div>
        <div class="row">
          <!--<a class="btn btn-success btn-sm btn-block sign_up", new_user_registration_path>Sign up</a>-->
          <%= link_to "Sign up", new_user_registration_path, class: 'nav-link text-white btn btn-success btn-sm btn-block sign_up' %>
        </div>
      </div>
    </div>
  </div>
</div>
</html>

app/views/layouts/_errors.html.erb
<% if user.errors.any? %>
  <div id="error_explanation">
    <h3><%= pluralize(user.errors.count, "error") %> prohibited this obj from being saved:</h3>
    <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/_success.html.erb
<div class="col-md-auto">
  <%= flash[:notice] %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Challenge3</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

        <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">

          <script src="https://kit.fontawesome.com/fc3bd943f3.js" crossorigin="anonymous"></script>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body class="d-flex flex-column vh-100">

 <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container">
      <a class="navbar-brand" href="/"><span>Bookers</span></a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavDropdown">
        <ul class="navbar-nav ml-auto">
        <% if user_signed_in? %>
          <li>
            <%= link_to user_path(current_user),class: 'nav-link text-light' do %>
              <i class="fas fa-home"></i> Home
            <% end %>
          </li>
          <li>
            <%=  link_to users_path,class: 'nav-link text-light' do %>
              <i class="fas fa-users"></i> Users
            <% end %>
          </li>
          <li>
            <%=  link_to books_path ,class: 'nav-link text-light' do %>
              <i class="fas fa-book-open"></i> Books
            <% end %>
          </li>
          <li>
            <%= link_to destroy_user_session_path, method: :delete,class: 'nav-link text-light' do %>
              <i class="fas fa-sign-out-alt"></i> logout
            <% end %>
          </li>
        <% else %>
          <li>
            <%= link_to root_path,class: 'nav-link text-light' do %>
              <i class="fas fa-home"></i> Home
            <% end %>
          </li>
          <li>
            <%= link_to about_path,class: 'nav-link text-light' do %>
              <i class="fas fa-link"></i> About
            <% end %>
          </li>
          <li>
            <%= link_to new_user_registration_path,class: 'nav-link text-light' do %>
              <i class="fas fa-user-plus"></i> sign up
            <% end %>
          </li>
          <li>
            <%= link_to new_user_session_path ,class: 'nav-link text-light' do %>
              <i class="fas fa-sign-in-alt"></i> login
            <% end %>
          </li>
        <% end %>
        </ul>
      </div>
    </div>
  </nav>























<!--    <header>-->
<!--  <nav class="navbar navbar-expand-lg navbar-dark bg-dark">-->
<!--    <div class="container">-->
<!--      <a class="navbar-brand" href="/"><span>Bookers</span></a>-->
<!--      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">-->
<!--        <span class="navbar-toggler-icon"></span>-->
<!--      </button>-->
<!--      <div class="collapse navbar-collapse" id="navbarNavDropdown">-->
<!--        <ul class="navbar-nav ml-auto">-->
<!--        <% if user_signed_in? %>-->
<!--          <li>-->
<!--            <a class="nav-link text-light" href="/">-->
<!--              <i class="fas fa-home" aria-hidden="true"></i> Home</a>-->
<!--          </li>-->
<!--          <li>-->
<!--            <a class="nav-link text-light" href="/home/about">-->
<!--              <i class="fas fa-link" aria-hidden="true"></i> About</a>-->
<!--          </li>-->
<!--          <li>-->
<!--            <a class="nav-link text-light" href="/users/sign_up">-->
<!--              <i class="fas fa-user-plus" aria-hidden="true"></i> Sign up</a>-->
<!--          </li>-->
<!--          <li>-->
<!--            <a class="nav-link text-light" href="/users/sign_in">-->
<!--              <i class="fas fa-sign-in-alt" aria-hidden="true"></i> Log in</a>-->
<!--          </li>-->
<!--        <% else %>-->
<!--          <li>-->
<!--            <a class="nav-link text-light" href="/">-->
<!--              <i class="fas fa-home" aria-hidden="true"></i> Home</a>-->
<!--          </li>-->
<!--          <li>-->
<!--            <a class="nav-link text-light" href="/home/about">-->
<!--              <i class="fas fa-link" aria-hidden="true"></i> Users</a>-->
<!--          </li>-->
<!--          <li>-->
<!--            <a class="nav-link text-light" href="/users/sign_up">-->
<!--              <i class="fas fa-user-plus" aria-hidden="true"></i> Books</a>-->
<!--          </li>-->
<!--          <li>-->
<!--              <i class="fas fa-sign-in-alt" aria-hidden="true"></i> Log out</a>-->
<!--          </li>-->
<!--        <% end %>-->
<!--        </ul>-->
<!--      </div>-->
<!--    </div>-->
<!--  </nav>-->
<!--</header>-->



      <!--<header class="bg-dark text-white ">-->
      <!--  <nav class="navbar navbar-expand-lg navbar-dark bg-dark">-->
      <!--    <div class="container">-->
      <!--      <a class="navbar-brand text-white p-3" href="/">Bookers</a>-->
      <!--      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="true" aria-label="Toggle navigation">-->
      <!--        <span class="navbar-toggler-icon"></span>-->
      <!--      </button>-->

      <!--      <div class="collapse navbar-collapse" id="navbarNavDropdown">-->
      <!--        <ul class="navbar-nav ml-auto">-->
      <!--        <% if user_signed_in? %>-->
      <!--        <li class="nav-item">-->
      <!--          <%= link_to "Home", "/", class: 'nav-link text-white' %>-->
      <!--        </li>-->
      <!--        <li class="nav-item">-->
      <!--          <%= link_to "Users", about_path, class: 'nav-link text-white' %>-->
      <!--        </li>-->
      <!--        <li class="nav-item">-->
      <!--          <%= link_to "Books", new_user_registration_path, class: 'nav-link text-white' %>-->
      <!--        </li>-->
      <!--        <li class="nav-item">-->
      <!--          <%= link_to "Log out", destroy_user_session_path, method: :delete, class: 'nav-link text-white' %>-->
      <!--        </li>-->

      <!--        <% else %>-->
      <!--        <li class="nav-item">-->
      <!--          <%= link_to "Home", "/", class: 'nav-link text-white' %>-->
      <!--        </li>-->
      <!--        <li class="nav-item">-->

      <!--          <%= link_to "About", about_path, class: 'nav-link text-white' %>-->
      <!--        </li>-->
      <!--        <li class="nav-item">-->
      <!--          <%= link_to "Sign up", new_user_registration_path, class: 'nav-link text-white' %>-->
      <!--        </li>-->
      <!--        <li class="nav-item">-->
      <!--          <%= link_to "Log in", new_user_session_path, class: 'nav-link text-white' %>-->
      <!--        </li>-->
      <!--        <% end %>-->
      <!--        </ul>-->
      <!--      </div>-->
      <!--    </div>-->
      <!--  </nav>-->
      <!--</header>-->

    <main >

      <%= yield %>
    </main>
    <footer>
      <div class="container mt5">
        <div class="row ">
          <div class="mx-auto">
            <p>CopyRight Infratop.inc</p>
          </div>
        </div>
      </div>
    </footer>


</html>

app/views/users/_index.html.erb
<table class='table'>
  <thead>
    <tr>
      <th>image</th>
      <th>name</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% users.each do |user| %>
      <tr>
        <td><%= image_tag user.get_profile_image("50x50") %></td>
        <td><%= user.name %></td>
        <td><%= link_to 'Show', user, class: "user_#{user.id}" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/users/_info.html.erb
<table class='table'>
  <tr><%= image_tag user.get_profile_image("100x100") %></tr>
  <tr>
	  <th>name</th>
	  <th><%= user.name %></th>
  </tr>
  <tr>
	  <th>introduction</th>
	  <th><%= user.introduction %></th>
  </tr>
</table>
　
<div class='row'>
  <%= link_to edit_user_path(user), class: "btn btn-outline-secondary btn-block edit_user_#{user.id}" do %>
    <i class="fas fa-user-cog"></i>
  <% end %>
</div>

app/views/users/edit.html.erb
<div class='container'>


  <div class='row'>
    <div class="mx-auto">
    <h2></br>User in</h2>
    <%= form_with model:@user, local:true do |f| %>
      <div class="mx-auto">
        <% if @user.errors.any? %>
          <div id="error_explanation">
            <h3><%= pluralize(@user.errors.count, "error") %> prohibited this obj from being saved:</h3>
            <ul>
              <% @user.errors.full_messages.each do |message| %>
                <li><%= message %></li>
              <% end %>
            </ul>
          </div>
        <% end %>
      </div>
      <div >
        <%= f.label :name %>
        </br>
        <%= f.text_field :name %>
        </br>
        <%= f.label :image %>
        </br>
        <%= f.file_field :profile_image, accept: 'image/jpeg' %>
        </br>
        <%= f.label :introduction %>
        </br>
        <%= f.text_area :introduction %>
        </br>
        <%= f.submit %>
    <% end %>
  </div>
</div>

app/views/users/index.html.erb
<div class='container'>
  <div class='row'>
    <div class='col-md-3'>
      <h2>User info</h2>
      <%= render 'info', user: current_user %>
      <h2 class="mt-3">New book</h2>
      <%= render 'books/form', book: @book %>
    </div>
    <div class='col-md-8 offset-md-1'>
      <h2>Users</h2>
      <%= render 'index',users: @users %>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class='container'>
     <%= render 'layouts/success' %>

  <div class='row'>
    <div class='col-md-3'>
      <h2>User info</h2>
      <%= render 'info', user: @user %>
      <h2 class="mt-3">New book</h2>
      <%= render 'books/form', book: @book %>
    </div>
    <div class='col-md-8 offset-md-1'>
      <h2>Books</h2>
      <%= render 'books/index',books: @books %>
    </div>
  </div>
</div>